# Generated by Django 5.1.2 on 2024-10-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_remove_product_stock_alter_product_name_productimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="ordered_at",
            new_name="ordered_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
